output:
	gcc -pthread prod_cons.c -o prod_cons

run:
	./prod_cons
	
clearLog:
	rm Producer_BLACK.txt Producer_RED.txt Producer_WHITE.txt Consumer.txt
	
clean:
	rm Producer_BLACK.txt Producer_RED.txt Producer_WHITE.txt Consumer.txt prod_cons